repos:
  # Hooks specific to `hfweb`.
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        files: "^site/"
      - id: check-json
        files: "^site/"
      - id: check-added-large-files
        files: "^site/"
      - id: mixed-line-ending
        files: "^site/"
      - id: detect-private-key
        files: "^site/"
      - id: check-merge-conflict
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: ./scripts/pnpm-run.sh
        language: script
        pass_filenames: false
        args: [format]
      - id: tsc
        name: typescript
        entry: ./scripts/pnpm-run.sh
        language: script
        pass_filenames: false
        args: [tscheck]
      - id: eslint
        name: eslint
        entry: ./scripts/pnpm-run.sh
        language: script
        pass_filenames: false
        args: [lint]
